### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by hasufell** [axelf4/vim-haskell#1]
When I press `<C-T>` with the code from the README gif... nothing happens. When I remove the plugin, then `<C-T>` indents as expected again. I haven't really tried with a minimal config yet. Is there anything that could conflict?

I think it's https://github.com/neovimhaskell/haskell-vim

**Comment by axelf4** [comment]
Thanks for opening this issue. I can confirm that neovimhaskell/haskell-vim conflicted. Please try it now, and make sure that this plugin comes earlier in `'runtimepath'`.

**Comment by hasufell** [comment]
Ok, seems it's somewhat working. But here's another problem:

```hs
updateWalletPassphrase
    :: forall ctx s k.
        ( HasDBLayer s k ctx
        , WalletKey k
        )
    => ctx
    -> WalletId
    -> (Passphrase "raw", Passphrase "raw")
    -> ExceptT ErrUpdatePassphrase IO ()
updateWalletPassphrase ctx wid (old, new) =
    withRootKey @ctx @s @k ctx wid (coerce old) ErrUpdatePassphraseWithRootKey
        $ \xprv scheme -> withExceptT ErrUpdatePassphraseNoSuchWallet $ do
            -- NOTE
            -- /!\ Important /!\
            -- attachPrivateKeyFromPwd does use 'EncryptWithPBKDF2', so
            -- regardless of the passphrase current scheme, we'll re-encrypt
            -- it using the new scheme, always.
            let oldP = preparePassphrase scheme old
            let newP = preparePassphrase EncryptWithPBKDF2 new
            let xprv' = changePassphrase oldP newP xprv
            attachPrivateKeyFromPwd @ctx @s @k ctx wid (xprv', newP)
```

Adding a line after the last line and then pressing either of the for/back buttons does nothing. This makes the plugin kinda stuck.

----

Edit: weird enough, it seems if I delete some lines (e.g. the comments), then it's working again...

**Comment by axelf4** [comment]
Seems to be another conflict. The syntax file bundled with Vim uses `hsLine/-BlockComment` as syntax group names for comments, whereas neovimhaskell/haskell-vim uses `haskellLine/-BlockComment`, so comments end up not getting skipped when lexing. Will push a fix tomorrow.

**Comment by hasufell** [comment]
Another thing I noticed:

![vim-haskell](https://user-images.githubusercontent.com/1241845/91285625-c0d7e200-e78d-11ea-8c64-0e6393bf0767.gif)

When I disable this plugin, then there's no such indentation, only after the do.

![vim-haskell2](https://user-images.githubusercontent.com/1241845/91286138-5d9a7f80-e78e-11ea-8d8c-d61b770b4355.gif)

**Comment by axelf4** [comment]
Regarding the extra indentation: Currently it is meant to work that way, since
```haskell
bar
    baz
    foo
```
could either be a single expression or three statements, and when indenting a new line an indentation point strictly larger than the indent of the previous line is favored. With <kbd>Tab</kbd>/<kbd>BS</kbd> (at sol) bound to toggle indent I don't find it too bad.

An option could be added to favor keeping the indent, but then you'd be indenting too often instead. Not *too* keen on adding special-cases for the keywords, although that would fix it.
